name = "opensource-hub-api"
main = "index.ts"
compatibility_date = "2024-04-01"
account_id = "063b426850c4c65d45b0809040ec8a71"

# 公网已关闭，仅通过 Service Binding 内网访问
workers_dev = false

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "opensource-hub-db"
database_id = "9989fa14-ca29-46ef-8c9f-9ab55f6b47d7"

# 环境变量
[vars]
API_VERSION = "1.0.0"
